### ISSUE TITLE
FileNotFoundError when import mikeio

### ISSUE THREAD

**Issue by lihu8918** [DHI/mikeio#484]
**Describe the bug**
FileNotFoundError when import mikeio. The error shows as follow:

Traceback (most recent call last):

  File "D:\project\subplot_with_mikeio.py", line 11, in <module>
    import mikeio

  File "C:\Anaconda3\lib\site-packages\mikeio\__init__.py", line 29, in <module>
    from .dfs0 import Dfs0

  File "C:\Anaconda3\lib\site-packages\mikeio\dfs0.py", line 8, in <module>
    from mikecore.eum import eumQuantity

  File "C:\Anaconda3\lib\site-packages\mikecore\__init__.py", line 34, in <module>
    eumDLL.Init()

  File "C:\Anaconda3\lib\site-packages\mikecore\eum.py", line 1368, in Init
    eumDLL.Wrapper = ctypes.CDLL(os.path.join(eumDLL.libfilepath, "eum"))

  File "C:\Anaconda3\lib\ctypes\__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)

FileNotFoundError: Could not find module 'C:\Anaconda3\lib\site-packages\mikecore\bin\windows\eum' (or one of its dependencies). Try using the full path with constructor syntax.

**To Reproduce**
import mikeio

**Screenshots**

**System information:**
 - Anaconda 2022.10
 -  Spyder 5.2.2
 - Python 3.9.13
 - MIKE IO version 1.2.4

**Comment by ecomodeller** [comment]
Do you have MIKE Zero installed?

Otherwise you need to install VC++ redist
<https://dhi.github.io/mikeio/#requirements>
