### ISSUE TITLE
matplotlib should be optional

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#647]
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'
>>> import mikeio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/src/mikeio/mikeio/__init__.py", line 31, in <module>
    from .dataset import DataArray, Dataset
  File "/home/jan/src/mikeio/mikeio/dataset/__init__.py", line 1, in <module>
    from ._dataarray import DataArray
  File "/home/jan/src/mikeio/mikeio/dataset/_dataarray.py", line 54, in <module>
    from .._spectral import calc_m0_from_spectrum
  File "/home/jan/src/mikeio/mikeio/_spectral.py", line 4, in <module>
    from matplotlib.axes import Axes
ModuleNotFoundError: No module named 'matplotlib'
```

**Comment by ecomodeller** [comment]
We actually need matplotlib for several things, it will be made mandatory.
