### ISSUE TITLE
Problem after updating the mikeio module

### ISSUE THREAD

**Issue by Elsafti** [DHI/mikeio#92]
**Describe the bug**
I get this error after updating mikeio today

`Installing collected packages: pycparser, pythonnet, numpy, six, python-dateutil, pytz, pandas, mikeio
    Running setup.py install for mikeio ... done
Successfully installed mikeio-0.5.3 numpy-1.19.2 pandas-1.1.2 pycparser-2.20 python-dateutil-2.8.1 pythonnet-2.5.1 pytz-2020.1 six-1.15.0

(tutorial-env) (base) C:\Users\hels>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mikeio
>>> exit()

(tutorial-env) (base) C:\Users\hels>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mikeio.eum import TimeStep, ItemInfo, EUMType, EUMUnit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TimeStep' from 'mikeio.eum' (C:\Users\hels\tutorial-env\lib\site-packages\mikeio\eum.py)
>>> from mikeio import Dfs0
>>> from mikeio.eum import TimeStep, ItemInfo, EUMType, EUMUnit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TimeStep' from 'mikeio.eum' (C:\Users\hels\tutorial-env\lib\site-packages\mikeio\eum.py)
>>>`

**To Reproduce**
1. install mikeio from repo
2. from mikeio.eum import TimeStep, ItemInfo, EUMType, EUMUnit

Include code snippet

**Expected behavior**
As it is not changed in the Jupyter notebooks I assume it is still the way to import mikeio for dfs0 files.

**Screenshots**

**System information:**
 - Python 3.7
 - MIKE version 2019/2020

**Comment by Elsafti** [comment]
I see now TimeStep is renamed to TimeStepUnit. Can you kindly update the notebook?

**Comment by Elsafti** [comment]
Thanks a lot!
