### ISSUE TITLE
Write Dfs0 with data of type float32 fails

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#95]
**Describe the bug**

**To Reproduce**
```
❯ python
Python 3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from mikeio import Dfs0
>>> float_array = np.array([0.0, 1.0],dtype=np.float32)
>>> dfs = Dfs0()
>>> dfs.write("test.dfs0", [float_array])
C:\Users\JAN\code\mikeio\mikeio\dfs0.py:325: UserWarning: No items info supplied. Using Item 1, 2, 3,...
  warnings.warn("No items info supplied. Using Item 1, 2, 3,...")
C:\Users\JAN\code\mikeio\mikeio\dfs0.py:338: UserWarning: No start time supplied. Using current time: 2020-09-24 11:26:36.187013 as start time.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\JAN\code\mikeio\mikeio\dfs0.py", line 358, in write
    Dfs0Util.WriteDfs0DataDouble(dfs, t_seconds, data_to_write)
TypeError: No method matches given arguments for WriteDfs0DataDouble: (<class 'DHI.Generic.MikeZero.DFS.DfsFile'>, <class 'list'>, <class 'System.Single[,]'>)
```
**Expected behavior**

The `write` method should handle conversion to double precision.
It should not be necessary to convert to double precision like this.
```
>>> dfs.write("test_double.dfs0", [float_array.astype(np.float64)])
```

**System information:**
 - Python 3.8.3
 - MIKE 2020

**Comment by ecomodeller** [comment]
Closed by 06fa64d5f50b6c9347d6f56a45fd0a8ac1aacd0d
